# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Site specific
title: Friends of Russia Dock Woodland
purpose: To protect, enhance, and promote Russia Dock Woodland for the enjoyment of all
bio: Friends of Russia Dock Woodland Bio
description: The official homepage of Friends of Russia Dock Woodland.

# Site specific: how many posts to display at home page?
posts_limits: 2

# Credit footer (foot.html) - populate this to form the string at the bottom
client: Friends of Russia Dock Woodland

# Deployment specific
#
# Option 1 - use github domain. e.g. https://atlas7.github.io/fordworg
#baseurl: "/fordworg"
#url: "https://atlas7.github.io"
#
# Option 2 - use custom domain. e.g. http://fordw.org
url: "/"

# Jekyll
locale: en_US

# Define how individual post URL looks.
# e.g. a post with a name like this: 2016-11-28-placeholder-1.md
# ... will have a URL looke this: http://fungai.org/2016/11/28/placeholder-1
# Note, the following value is equivalent to "pretty"
permalink: /:year/:month/:day/:title/


# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true

# This comes with the massively theme. Don't think it is used.
sass:
  sass_dir:         _sass
  style:            compressed

# Comments (Comment out if not used)
#disqus_shortname:

# Site specific social contacts. Only used in Contact section
# leave blank to hide icon
#analytics-id:
twitter: friendsrdw
#facebook:
#instagram:
#githubid:
location: Russia Dock Woodland
chairman: Steve Cornish
phone1: +44 20 7237 7586
phone2: +44 79 4727 5386
email: "fordw.org@gmail.com"

# Messages sent via website message box will send to here (via formspree.io)
# Reference: https://formspree.io/
email2: "fordw.org@gmail.com"

# Jekyll-paginate - how many blog posts displayed per page (used in blog section)
paginate: 8
paginate_path: "/blog/page:num/"

# Comes with Massively Theme. Note quite sure if this is used.
jekyll-mentions:
  base_url: https://github.com

# Exclude list. Comes with Massively Theme.
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
