# Site
title: Friends of Russia Dock Woodland
purpose: To protect, enhance, and promote Russia Dock Woodland for the enjoyment of all
bio: Friends of Russia Dock Woodland Bio
description: The official homepage of Friends of Russia Dock Woodland.

# index.html - how many posts to display at home page?
posts_limits: 10

# Credit footer (foot.html) - populate this to form the string at the bottom
# Further developed by [developer](developer_github) for client
client: Friends of Russia Dock Woodland
developer: atlas7
developer_github: https://github.com/Atlas7

locale: en_US
baseurl: "/fordworg" # the subpath of your site, e.g. /blog
url: "https://atlaas7.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   # leave blank to hide icon

# Social
#analytics-id:
twitter: friendsrdw  # leave blank to hide icon
facebook:   # leave blank to hide icon
instagram:   # leave blank to hide icon
github:   # leave blank to hide icon

# This is displayed on website footer
location: Russia Dock Woodland
chairman: Steve Cornish
phone1: +44 20 7237 7586
phone2: +44 79 4727 5386

# This is displayed on website footer
email: "fordw.org@gmail.com"

# Messages sent via website message box will send to here (via formspree.io)
# Reference: https://formspree.io/
email2: "fordw.org@gmail.com"

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
