# Site
title: Friends of Russia Dock Woodland
purpose: To protect, enhance, and promote Russia Dock Woodland for the enjoyment of all
bio: Friends of Russia Dock Woodland Bio
description: >
  The Friends of Russia Dock Woodland (FRDW) are a group of residents who help to protect and enhance the woodland
  and Stave Hill ecological park, which together run through the middle of the Rotherhithe peninsula.
  We address everything from damaged signage and rubbish management to development planning applications which
  impact on the local ecology.


locale: en_US
baseurl: "/fordworg" # the subpath of your site, e.g. /blog
url: "https://atlaas7.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id: ""
twitter: jAtlas7
facebook: johnnychan0302
instagram: jatlas7
github: atlas7

# This is displayed on website footer
location: Russia Dock Woodland
chairman: Steve Cornish
phone1: +44 20 7237 7586
phone2: +44 79 4727 5386

# This is displayed on website footer
email: "fordw.org@gmail.com"

# Messages sent via website message box will send to here (via formspree.io)
# Reference: https://formspree.io/
email2: "fordw.org@gmail.com"

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
